version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/project/public:cached
    links:
      - booking_app
    networks:
      - frontend
  booking_app:
    build: ./
    volumes:
      - ./:/project:cached
    working_dir: /project
    networks:
      - frontend
      - backend
    environment:
      APP_ENV: local
      APP_KEY: "base64:05VNDWbv5axaVCzWrtTBLMV1T1Ex8ML4dNzWINrWXHY="
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: booking_app_Db
      DB_USERNAME: root
      DB_PASSWORD: password
  mysql:
    image: mysql/mysql-server:8.0.28
    command: --max_allowed_packet=1G --skip-log-bin --innodb_flush_log_at_trx_commit=2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: booking_app_Db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./:/project:ro
    working_dir: /project
    networks:
      - backend

networks:
  frontend:
  backend:
